spring.application.name=dealz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dealz?createDatabaseIfNotExist=true
spring.datasource.username=${db_user}
spring.datasource.password=${db_password}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
server.servlet.context-path = /api

jwt.secret-key = ${Secret_key}

# Stockage des images uploadées
app.upload.dir=${user.home}/dealz-uploads/images

# Limites multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB